#!/bin/bash

# Trigger Railway Redeploy
# This script provides instructions for manual redeployment

echo "Railway Redeployment Instructions"
echo "================================="
echo ""
echo "To manually trigger a redeploy on Railway:"
echo ""
echo "1. Open Railway Dashboard: https://dashboard.railway.app"
echo "2. Navigate to your project: physical-ai-robotics-textbook"
echo "3. Click on the backend service"
echo "4. Click on the 'Settings' tab"
echo "5. Scroll down to 'Deploy'"
echo "6. Click 'Redeploy' button"
echo ""
echo "Alternatively, you can:"
echo "1. Make a small change to any file (e.g., add a comment)"
echo "2. Commit and push to trigger automatic redeploy"
echo ""
echo "Current deployment should be running:"
echo "- main_auth_only.py (lightweight auth server)"
echo "- auth_standalone.py (standalone auth router)"
echo "- Health check timeout: 2000ms (updated from 100ms)"
echo ""
echo "Expected API message when deployed:"
echo "\"Physical AI & Humanoid Robotics Textbook API - Auth Only\""
echo ""
echo "To check deployment status, run:"
echo "curl https://physical-ai-robotics-textbook-production.up.railway.app/"
echo ""
echo "To check health endpoint:"
echo "curl -w \"\\nTime: %{time_total}s\" https://physical-ai-robotics-textbook-production.up.railway.app/health"